
server:
  port: 9050
  contextPath: /v2/world/client

logging:
  level:
    org.world.client.controllers: INFO
info:
  app:
    name: WorldRS Client Application  V2
    description: Detail of Countrys, Citys, Region, Languages .... etc around the world.
    version: 2.0.1    
spring:
  application:
    name: worldclient-v2
    instance_id: i001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true