
server:
  port: 9050
  contextPath: /v1/world/client

logging:
  level:
    org.world.client.controllers: INFO
spring:
  application:
    name: worldclient-v1
    instance_id: 001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true